import type { NextPage } from "next";
import { Card } from "../../components";
import Head from "next/head";

const NinetyEightLabs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>98 Labs Coding Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container">
        <h3 className="py-3">98 Labs Coding Exercises</h3>
        <div className="row">
          <Card
            title="XYZ Problem"
            expectations="The difficulty level of this exercise depends on the level and
                liberties of the applicant - solutions can either be simple or
                complex. The applicant’s approach will show their creativity,
                proper understanding of the technology used, thought process,
                and critical thinking in solving the given problem set."
            address="Frontend or Backend Developer Applicants"
            url="/98labs/xyz-problem"
          ></Card>
          <Card
            title="Basic Layout 1"
            expectations="A Junior
            Frontend Developer should be able to accomplish this."
            address="Frontend Developer Applicants"
            url="/98labs/basic-layout-1"
          ></Card>
        </div>
      </section>
    </div>
  );
};

export default NinetyEightLabs;
